class ProductModel {
  final int id;
  final String name;
  final String image;
  final int reviews;
  final double rating;
  final double price;
  final double discountPrice;
  final String details;

  ProductModel(this.id, this.name,this.image, this.reviews, this.rating, this.price, this.discountPrice, this.details);

  static List<ProductModel> getProductList(){
    List<ProductModel> list = List<ProductModel>() ;
    list.add(ProductModel(1, 'Man T-Shirt',"https://previews.123rf.com/images/alexyakimvski/alexyakimvski1704/alexyakimvski170400050/75838319-male-model-in-a-suit-posing-in-front-of-a-wooden-wall.jpg", 49, 4.5, 27.00, 33.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus feugiat in ante metus dictum at tempor. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Urna neque viverra justo nec ultrices dui sapien eget mi. Ac auctor augue mauris augue. Ultrices in iaculis nunc sed augue lacus viverra. Tellus in metus vulputate eu scelerisque felis imperdiet. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Viverra vitae congue eu consequat ac felis. Viverra adipiscing at in tellus integer feugiat scelerisque. Turpis nunc eget lorem dolor sed. Erat imperdiet sed euismod nisi porta lorem mollis.'));
    list.add(ProductModel(2, 'Woman T-Shirt', "https://media.gettyimages.com/photos/beautiful-woman-with-makeup-picture-id901642956", 49, 4.5, 27.00, 33.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus feugiat in ante metus dictum at tempor. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Urna neque viverra justo nec ultrices dui sapien eget mi. Ac auctor augue mauris augue. Ultrices in iaculis nunc sed augue lacus viverra. Tellus in metus vulputate eu scelerisque felis imperdiet. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Viverra vitae congue eu consequat ac felis. Viverra adipiscing at in tellus integer feugiat scelerisque. Turpis nunc eget lorem dolor sed. Erat imperdiet sed euismod nisi porta lorem mollis.'));
    list.add(ProductModel(3, 'Mens Fashion', "https://previews.123rf.com/images/alexyakimvski/alexyakimvski1704/alexyakimvski170400027/75830900-male-model-posing-.jpg", 39, 3.5, 26.00, 28.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus feugiat in ante metus dictum at tempor. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Urna neque viverra justo nec ultrices dui sapien eget mi. Ac auctor augue mauris augue. Ultrices in iaculis nunc sed augue lacus viverra. Tellus in metus vulputate eu scelerisque felis imperdiet. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Viverra vitae congue eu consequat ac felis. Viverra adipiscing at in tellus integer feugiat scelerisque. Turpis nunc eget lorem dolor sed. Erat imperdiet sed euismod nisi porta lorem mollis.'));
    list.add(ProductModel(4, 'Man T-Shirt', "https://previews.123rf.com/images/alexyakimvski/alexyakimvski1704/alexyakimvski170400013/75752720-male-model-in-a-suit-posing-indoors.jpg", 59, 5.0, 26.00, 28.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus feugiat in ante metus dictum at tempor. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Urna neque viverra justo nec ultrices dui sapien eget mi. Ac auctor augue mauris augue. Ultrices in iaculis nunc sed augue lacus viverra. Tellus in metus vulputate eu scelerisque felis imperdiet. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Convallis posuere morbi leo urna molestie at elementum eu facilisis. Viverra vitae congue eu consequat ac felis. Viverra adipiscing at in tellus integer feugiat scelerisque. Turpis nunc eget lorem dolor sed. Erat imperdiet sed euismod nisi porta lorem mollis.'));
    return list;
  }
}